# Generated by Django 3.1 on 2021-03-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_detail_invoice_distributor_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail_invoice',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
