# Generated by Django 3.1 on 2021-03-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_auto_20210321_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box_budget', models.FloatField()),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=16)),
                ('cc', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('fk_point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.point')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_invoice', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=250)),
                ('cost', models.FloatField()),
                ('iva', models.FloatField()),
                ('fk_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.distributor')),
                ('fk_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.point')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='distributor',
            name='fk_item',
            field=models.ManyToManyField(to='inventory.Item'),
        ),
        migrations.CreateModel(
            name='Detail_invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('fk_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice')),
                ('fk_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'Detail_invoice',
                'verbose_name_plural': 'Details_invoice',
            },
        ),
    ]
